version: '3.8'

name: pretendify
services:
    website:
        environment:
            - FLASK_APP=app.py
            - FLASK_RUN_HOST=0.0.0.0
        network_mode: bridge
        working_dir: /app
        ports:
            - 2011:5000
        restart: always
        tty: true
        image: stijnch/pretendify-website:latest
        env_file:
            - stack.env